name: tele_crm_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  awesome_dialog: ^3.1.0
  audioplayers: ^6.1.0
  chat_bubbles: ^1.5.0
  dart_ipify: ^1.1.1
  device_info_plus: ^11.3.0
  dio: ^5.3.2
  dotted_border: ^2.0.0+3
  dropdown_button2: ^2.3.8
  file_picker: ^10.2.0
  file_saver: ^0.2.6
  # firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  # firebase_messaging: ^15.1.5
  # firebase_analytics: ^11.3.5
  # firebase_crashlytics: ^4.1.5
  # firebase_performance: ^0.10.0+11
  # firebase_remote_config: ^5.1.0
  flutter_bloc: ^8.1.3
  # flutter_local_notifications: ^18.0.1
  flutter_svg: ^2.0.10+1
  flutter_widget_from_html: ^0.15.3
  get_it: ^8.0.2
  go_router: ^14.6.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.0
  loader_overlay: ^4.0.3
  location: ^7.0.1
  geolocator: ^13.0.4
  geolocator_android: 4.6.1
  # location2: ^6.0.4
  logger: ^2.0.1
  open_file: ^3.3.2
  package_info_plus: ^8.1.1
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  socket_io_client: ^3.0.2
  sticky_headers: ^0.3.0+2
  super_banners: ^0.0.1
  table_calendar: ^3.0.9
  url_launcher: ^6.1.12
  pod_player: ^0.2.1
  mime: ^2.0.0
  uuid: ^4.3.3
  connectivity_plus: ^6.0.3
  # flutter_barcode_scanner: ^2.0.0
  # background_locator_2: ^2.0.6
  flutter_secure_storage: ^9.0.0
  path_provider: ^2.0.8
  pub_semver: ^2.1.4
  flutter_colorpicker: ^1.0.3
  flutter_rating_bar: ^4.0.1
  awesome_notifications: ^0.10.1
  syncfusion_flutter_core: ^28.1.36
  syncfusion_flutter_pdfviewer: ^28.1.36
  syncfusion_flutter_datepicker: ^28.1.36
  syncfusion_flutter_signaturepad: ^28.1.36
  syncfusion_flutter_charts: ^28.1.36
  syncfusion_flutter_maps: ^28.1.36
  flutter_fancy_tree_view: ^1.4.1
  fl_chart: ^0.66.2
  photo_view: ^0.14.0
  flutter_ripple: ^0.0.3
  image_picker: ^1.1.1
  video_thumbnail: ^0.5.3
  toggle_switch: ^2.3.0
  sticky_infinite_list: ^4.0.1
  flutter_linkify: ^6.0.0
  google_maps_flutter: ^2.6.1
  flutter_staggered_grid_view: ^0.7.0
  map_launcher: ^3.3.1
  scrollview_observer: ^1.21.0
  local_auth: ^2.2.0
  http_parser: ^4.0.2
  cached_network_image: ^3.4.0
  # ffmpeg_kit_flutter_full_gpl: ^6.0.3
  dart_jsonwebtoken: ^2.14.1
  workmanager: ^0.8.0
  # stream_video: ^0.6.0
  # stream_video_flutter: ^0.6.0
  # stream_video_push_notification: ^0.6.0
  pinput: ^5.0.0
  equatable: ^2.0.7
  gap: ^3.0.1
  camera: ^0.11.2
  action_slider: ^0.7.0
  geocoding: ^4.0.0
  flutter_inappwebview: ^6.0.0
  supabase_flutter: ^2.9.1
  flutter_phone_direct_caller: ^2.2.1
  # ffmpeg_kit_flutter:
  #   git:
  #     url: https://github.com/Sahad2701/ffmpeg-kit.git
  #     path: flutter/flutter
  #     ref: flutter_fix_retired_v6.0.3

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0


dependency_overrides:
  meta: ^1.10.0
  url_launcher_ios: ^6.3.1
  test_api: ^0.6.1

flutter_launcher_icons:
  ios: true
  remove_alpha_ios: true
  android: 'ic_launcher'
  image_path: 'assets/images/home_revise_tele_crm.png'
  image_path_ios: 'assets/images/home_revise_tele_crm.png'
  adaptive_icon_background: '#FFFFFF'

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700

    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700

    - family: Levenim
      fonts:
        - asset: assets/fonts/levenim/Levenim-Regular.ttf
          weight: 400

    - family: Nioicon
      fonts:
        - asset: assets/fonts/nioicon/Nioicon.ttf

flutter_assets:
  assets_path: assets/
  output_path: lib/src/core/utils/
  filename: assets.dart